module.exports = {
  apps: [
    {
      name: 'sportsphere',
      script: '.next/standalone/server.js',
      interpreter: 'node',
      cwd: '/var/www/sportsphere-nextjs',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
        HOSTNAME: '0.0.0.0',
      },
      out_file: '/var/log/pm2/sportsphere-out.log',
      error_file: '/var/log/pm2/sportsphere-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
    },
    {
      name: 'sportsphere-admin',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3003',
      cwd: '/var/www/sportsphere-nextjs/Admin',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
        HOSTNAME: '0.0.0.0',
      },
      out_file: '/var/log/pm2/sportsphere-admin-out.log',
      error_file: '/var/log/pm2/sportsphere-admin-err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      watch: false,
    },
    {
      name: 'sportsphere-ws',
      script: 'scripts/ws-server.mjs',
      cwd: '/var/www/sportsphere-nextjs',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        WS_PORT: 3004,
      },
      out_file: '/var/log/pm2/sportsphere-ws-out.log',
      error_file: '/var/log/pm2/sportsphere-ws-err.log',
      watch: false,
    },
  ],
};
