// File generated by FlutterFire CLI / or placeholder until you run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=sportsphere-v1
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// After running `flutterfire configure --project=sportsphere-v1`, this file
/// is replaced with real values. Until then, [isConfigured] is false.
class DefaultFirebaseOptions {
  static bool get isConfigured {
    final o = currentPlatform;
    return o.apiKey.isNotEmpty &&
        o.apiKey != 'REPLACE_ME' &&
        o.projectId.isNotEmpty &&
        o.projectId != 'REPLACE_ME';
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'run flutterfire configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Placeholder values — run `flutterfire configure --project=sportsphere-v1`
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sportsphere-v1',
    authDomain: 'sportsphere-v1.firebaseapp.com',
    storageBucket: 'sportsphere-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sportsphere-v1',
    storageBucket: 'sportsphere-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sportsphere-v1',
    storageBucket: 'sportsphere-v1.appspot.com',
    iosBundleId: 'com.sportsphere.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sportsphere-v1',
    storageBucket: 'sportsphere-v1.appspot.com',
    iosBundleId: 'com.sportsphere.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sportsphere-v1',
    storageBucket: 'sportsphere-v1.appspot.com',
  );
}
