declare module "lucide-react-native" {
  import { ComponentType } from "react";
  type IconProps = { size?: number; color?: string; style?: any; [key: string]: any };
  type IconComp = ComponentType<IconProps>;
  export type LucideIcon = IconComp;
  const Icon: IconComp;
  export default Icon;
  export const Home: IconComp;
  export const Trophy: IconComp;
  export const PlusCircle: IconComp;
  export const Bell: IconComp;
  export const User: IconComp;
  export const Search: IconComp;
  export const ChevronLeft: IconComp;
  export const ChevronRight: IconComp;
  export const ChevronDown: IconComp;
  export const Send: IconComp;
  export const Heart: IconComp;
  export const Mail: IconComp;
  export const Lock: IconComp;
  export const Eye: IconComp;
  export const EyeOff: IconComp;
  export const X: IconComp;
  export const Check: IconComp;
  export const Crown: IconComp;
  export const UserCheck: IconComp;
  export const AtSign: IconComp;
  export const Medal: IconComp;
  export const TrendingUp: IconComp;
  export const TrendingDown: IconComp;
  export const Minus: IconComp;
  export const Clock: IconComp;
  export const MapPin: IconComp;
  export const Zap: IconComp;
  export const Target: IconComp;
  export const ShoppingBag: IconComp;
  export const BadgeCheck: IconComp;
  export const MessageCircle: IconComp;
  export const UserPlus: IconComp;
  export const ShieldCheck: IconComp;
  export const Hash: IconComp;
  export const Image: IconComp;
  export const Vote: IconComp;
  export const BarChart3: IconComp;
  export const AlertCircle: IconComp;
  export const Settings: IconComp;
  export const LogOut: IconComp;
  export const Calendar: IconComp;
  export const Camera: IconComp;
  export const Share2: IconComp;
  export const Bookmark: IconComp;
  export const FileText: IconComp;
  export const Activity: IconComp;
  export const Users: IconComp;
  export const ArrowLeft: IconComp;
}
