// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/"
type AppRouteHandlerRoutes = "/api/activity" | "/api/auth" | "/api/auth/forgot-password" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/auth/reset-password" | "/api/auth/verify-email/confirm" | "/api/auth/verify-email/request" | "/api/comments" | "/api/communities" | "/api/feed" | "/api/follows" | "/api/leaderboard" | "/api/likes" | "/api/matches" | "/api/messages" | "/api/notifications" | "/api/polls/vote" | "/api/posts" | "/api/profile" | "/api/profile-data" | "/api/profile/favorites" | "/api/roles" | "/api/roles/[id]/types" | "/api/roles/upgrade" | "/api/sports" | "/api/sports/[slug]" | "/api/sports/[slug]/competitions" | "/api/sports/[slug]/fixtures" | "/api/sports/[slug]/standings" | "/api/sports/[slug]/teams" | "/api/sports/[slug]/top-scorers" | "/api/sports/follow" | "/api/spotlight" | "/api/standings" | "/api/users"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/activity": {}
  "/api/auth": {}
  "/api/auth/forgot-password": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/auth/verify-email/confirm": {}
  "/api/auth/verify-email/request": {}
  "/api/comments": {}
  "/api/communities": {}
  "/api/feed": {}
  "/api/follows": {}
  "/api/leaderboard": {}
  "/api/likes": {}
  "/api/matches": {}
  "/api/messages": {}
  "/api/notifications": {}
  "/api/polls/vote": {}
  "/api/posts": {}
  "/api/profile": {}
  "/api/profile-data": {}
  "/api/profile/favorites": {}
  "/api/roles": {}
  "/api/roles/[id]/types": { "id": string; }
  "/api/roles/upgrade": {}
  "/api/sports": {}
  "/api/sports/[slug]": { "slug": string; }
  "/api/sports/[slug]/competitions": { "slug": string; }
  "/api/sports/[slug]/fixtures": { "slug": string; }
  "/api/sports/[slug]/standings": { "slug": string; }
  "/api/sports/[slug]/teams": { "slug": string; }
  "/api/sports/[slug]/top-scorers": { "slug": string; }
  "/api/sports/follow": {}
  "/api/spotlight": {}
  "/api/standings": {}
  "/api/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
