// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/api/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/verify-email/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email/confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/verify-email/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/verify-email/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email/request">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/verify-email/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/communities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities">> = Specific
  const handler = {} as typeof import("../../../src/app/api/communities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feed">> = Specific
  const handler = {} as typeof import("../../../src/app/api/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/follows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follows">> = Specific
  const handler = {} as typeof import("../../../src/app/api/follows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leaderboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/likes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/likes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/likes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/polls/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/polls/vote">> = Specific
  const handler = {} as typeof import("../../../src/app/api/polls/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/profile-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile-data">> = Specific
  const handler = {} as typeof import("../../../src/app/api/profile-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/profile/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/favorites">> = Specific
  const handler = {} as typeof import("../../../src/app/api/profile/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/roles/[id]/types/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles/[id]/types">> = Specific
  const handler = {} as typeof import("../../../src/app/api/roles/[id]/types/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles">> = Specific
  const handler = {} as typeof import("../../../src/app/api/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/roles/upgrade/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles/upgrade">> = Specific
  const handler = {} as typeof import("../../../src/app/api/roles/upgrade/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sports/[slug]/competitions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sports/[slug]/competitions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sports/[slug]/competitions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sports/[slug]/fixtures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sports/[slug]/fixtures">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sports/[slug]/fixtures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sports/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sports/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sports/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sports/[slug]/standings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sports/[slug]/standings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sports/[slug]/standings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sports/[slug]/teams/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sports/[slug]/teams">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sports/[slug]/teams/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sports/[slug]/top-scorers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sports/[slug]/top-scorers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sports/[slug]/top-scorers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sports/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sports/follow">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sports/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sports">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/spotlight/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spotlight">> = Specific
  const handler = {} as typeof import("../../../src/app/api/spotlight/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/standings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/standings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/standings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
