-- restore-ali-simba.sql
-- Restores the one real fan user (Ali Simba) that was accidentally deleted
-- All other 1840 deleted accounts were fake @sportssphere.fun team/player entities

INSERT INTO "User" (
  id, name, email, handle, "passwordHash", "role", "verificationStatus", "isVerified",
  bio, location, "coverGradient", "followerCount", "followingCount", "postCount",
  "registeredAt", "updatedAt", "lastSeenAt", "aboutMe", city, "countryOfOrigin",
  "currentCountry", "dateOfBirth", "emailVerified", "emailVerifyExpiry",
  "emailVerifyToken", "fontSize", gender, "highContrast", interests, "isPro",
  nationality, "notifPrefs", phone, preferences, "preferredLanguage",
  "privacySettings", pronouns, "reducedMotion", region,
  "roleId", "roleProfile", "roleTypeId",
  theme, "roleData", "sportsFollowing", "isBanned", "fanCount"
) VALUES (
  '30643f95-a879-4775-b902-0fb6af02cc72',
  'Ali Simba',
  '@alisimba',
  '@alisimba',
  '$2a$10$Kw/QEV/LTeWVk7Kr.c1vVujuoYZVWWZn/CaGhblC/HHVRljxyXMdO',
  'fan',
  'none',
  false,
  'Football is Simba',
  'Dar es salaam',
  'from-blue-600 to-blue-900',
  0, 3, 2,
  '2026-08-13 09:07:55.554',
  '2026-08-13 09:53:19.297',
  '2026-08-13 09:07:55.554',
  'Naipenda Simba Jamani',
  NULL,
  NULL,
  NULL,
  '1994-08-13',
  false,
  '2026-08-13 09:12:55.549',
  '445512',
  'medium',
  'Male',
  false,
  '["Transfers","Statistics","Fantasy","Live Scores","Local Football","International Football","Highlights"]'::jsonb,
  false,
  'Tanzania',
  '{}'::jsonb,
  NULL,
  '{}'::jsonb,
  'English',
  '{}'::jsonb,
  'he/him',
  false,
  NULL,
  'cfa8e1a2-6c81-4a22-a5c9-a35f20dafd1d',
  '{"fanTypes":{"primary":"diehard"}}'::jsonb,
  '7932576e-36c6-4fdd-baa2-143e8adb9ea6',
  'dark',
  '{}'::jsonb,
  '["Football"]'::jsonb,
  false,
  0
) ON CONFLICT (id) DO NOTHING;
