BEGIN;


UPDATE "Team" SET
  name = 'Azam FC',
  slug = 'azam-fc',
  venue = 'Azam Complex',
  city = 'Dar es Salaam',
  country = 'Tanzania',
  "countryCode" = 'TZ',
  "logoUrl" = 'https://img.a.transfermarkt.technology/wappen/head/28970.png?lm=1',
  "shortName" = 'AZAM',
  metadata = '{"stadiumSeats": 10000, "stadiumName": "Azam Complex", "squadSize": 34, "averageAge": 25.0, "foreigners": 16, "foreignerPercent": 47.1, "nationalTeamPlayers": 14, "transferRecord": -25000, "season": "2025/26"}'::jsonb,
  "updatedAt" = NOW()
WHERE id = 'ftz-azam';


INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "shirtNumber", metadata) VALUES ('ftz-azam-zuberifoba-0', 'Zuberi Foba', 'ftz-azam-zuberifoba-0', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'GK', 'admin', true, true, NOW(), NOW(), 'Zuberi', 'Foba', 'Tanzania', '2002-05-23'::timestamp, 32, '{"marketValueEUR": 200000}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", metadata) VALUES ('ftz-azam-aishisalummanula-1', 'Aishi Salum Manula', 'ftz-azam-aishisalummanula-1', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'GK', 'admin', true, true, NOW(), NOW(), 'Aishi', 'Salum Manula', 'Tanzania', '1995-09-13'::timestamp, 183, '{"foot": "left", "signedFrom": "Simba SC", "contract": "2028-06-30", "marketValueEUR": 150000, "joinedDate": "2025-07-09"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-issafofana-2', 'Issa Fofana', 'ftz-azam-issafofana-2', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'GK', 'admin', true, true, NOW(), NOW(), 'Issa', 'Fofana', 'Mali', '1992-06-15'::timestamp, '{"signedFrom": "Jeanne d''''Arc FC Bamako", "joinedDate": "2025-07-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-anthonyremmympemba-3', 'Anthony Remmy Mpemba', 'ftz-azam-anthonyremmympemba-3', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'GK', 'admin', true, true, NOW(), NOW(), 'Anthony', 'Remmy Mpemba', 'Tanzania', '2005-12-09'::timestamp, '{}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", "shirtNumber", metadata) VALUES ('ftz-azam-issafofana-4', 'Issa Fofana', 'ftz-azam-issafofana-4', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'GK', 'admin', true, true, NOW(), NOW(), 'Issa', 'Fofana', 'Cote d''Ivoire', '2004-01-30'::timestamp, 190, 1, '{"foot": "right", "signedFrom": "Al-Hilal Club (Omdurman)", "contract": "2027-06-30", "joinedDate": "2025-08-15"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", "shirtNumber", metadata) VALUES ('ftz-azam-lusajomwaikenda-5', 'Lusajo Mwaikenda', 'ftz-azam-lusajomwaikenda-5', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CB', 'admin', true, true, NOW(), NOW(), 'Lusajo', 'Mwaikenda', 'Tanzania', '2000-10-27'::timestamp, 174, 5, '{"foot": "right", "marketValueEUR": 150000}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "shirtNumber", metadata) VALUES ('ftz-azam-nurutwalib-6', 'Nuru Twalib', 'ftz-azam-nurutwalib-6', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CB', 'admin', true, true, NOW(), NOW(), 'Nuru', 'Twalib', 'Tanzania', '2005-01-28'::timestamp, 25, '{"signedFrom": "Azam FC U19", "marketValueEUR": 50000, "joinedDate": "2024-07-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-lamecklawi-7', 'Lameck Lawi', 'ftz-azam-lamecklawi-7', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CB', 'admin', true, true, NOW(), NOW(), 'Lameck', 'Lawi', 'Tanzania', '2005-09-12'::timestamp, '{"signedFrom": "Coastal Union", "marketValueEUR": 25000, "joinedDate": "2025-07-03"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", metadata) VALUES ('ftz-azam-henristanic-8', 'Henri Stanic', 'ftz-azam-henristanic-8', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CB', 'admin', true, true, NOW(), NOW(), 'Henri', 'Stanic', 'Belgium', '2002-07-18'::timestamp, 194, '{"foot": "right", "signedFrom": "Stellenbosch FC", "contract": "2027-06-30", "joinedDate": "2026-07-15"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", "shirtNumber", metadata) VALUES ('ftz-azam-yeisonfuentes-9', 'Yeison Fuentes', 'ftz-azam-yeisonfuentes-9', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CB', 'admin', true, true, NOW(), NOW(), 'Yeison', 'Fuentes', 'Colombia', '2002-07-11'::timestamp, 182, 24, '{"foot": "right", "signedFrom": "Leones FC", "joinedDate": "2024-01-13"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-abdallakheri-10', 'Abdalla Kheri', 'ftz-azam-abdallakheri-10', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CB', 'admin', true, true, NOW(), NOW(), 'Abdalla', 'Kheri', 'Tanzania', '1996-10-10'::timestamp, '{"signedFrom": "Ndanda FC", "joinedDate": "2017-01-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-lupinimawukudieumerci-11', 'Lupini Mawuku Dieumerci', 'ftz-azam-lupinimawukudieumerci-11', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CB', 'admin', true, true, NOW(), NOW(), 'Lupini', 'Mawuku Dieumerci', 'DR Congo', '2005-12-22'::timestamp, '{"signedFrom": "AS Maniema Union", "joinedDate": "2026-07-18"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", "shirtNumber", metadata) VALUES ('ftz-azam-ahoutouangenorzouzou-12', 'Ahoutou Angenor Zouzou', 'ftz-azam-ahoutouangenorzouzou-12', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CB', 'admin', true, true, NOW(), NOW(), 'Ahoutou', 'Angenor Zouzou', 'Cote d''Ivoire', '2001-05-27'::timestamp, 183, 27, '{"signedFrom": "AFAD-Plateau", "joinedDate": "2025-01-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", metadata) VALUES ('ftz-azam-taiwoabdulrafiu-13', 'Taiwo Abdulrafiu', 'ftz-azam-taiwoabdulrafiu-13', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'LB', 'admin', true, true, NOW(), NOW(), 'Taiwo', 'Abdulrafiu', 'Nigeria', '2002-04-20'::timestamp, 190, '{"foot": "left", "signedFrom": "Rivers United FC", "marketValueEUR": 125000, "joinedDate": "2026-07-23"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "shirtNumber", metadata) VALUES ('ftz-azam-pascalmsindo-14', 'Pascal Msindo', 'ftz-azam-pascalmsindo-14', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'LB', 'admin', true, true, NOW(), NOW(), 'Pascal', 'Msindo', 'Tanzania', '2003-08-15'::timestamp, 12, '{"foot": "left", "signedFrom": "Azam FC U19", "contract": "2027-06-30", "marketValueEUR": 75000, "joinedDate": "2022-07-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-ashrafushabanikibeku-15', 'Ashrafu Shabani Kibeku', 'ftz-azam-ashrafushabanikibeku-15', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'RB', 'admin', true, true, NOW(), NOW(), 'Ashrafu', 'Shabani Kibeku', 'Tanzania', '2006-12-20'::timestamp, '{}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", metadata) VALUES ('ftz-azam-donovanmakoma-16', 'Donovan Makoma', 'ftz-azam-donovanmakoma-16', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'DM', 'admin', true, true, NOW(), NOW(), 'Donovan', 'Makoma', 'France', '1999-02-01'::timestamp, 190, '{"foot": "right", "signedFrom": "Birkirkara FC", "marketValueEUR": 350000, "joinedDate": "2026-07-22"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", metadata) VALUES ('ftz-azam-himidmaomkami-17', 'Himid Mao Mkami', 'ftz-azam-himidmaomkami-17', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'DM', 'admin', true, true, NOW(), NOW(), 'Himid', 'Mao Mkami', 'Tanzania', '1992-11-05'::timestamp, 177, '{"foot": "right", "signedFrom": "Tala''''ea El Gaish", "contract": "2026-06-30", "joinedDate": "2025-07-10"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-mzeemzee-18', 'Mzee Mzee', 'ftz-azam-mzeemzee-18', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'MF', 'admin', true, true, NOW(), NOW(), 'Mzee', 'Mzee', 'Zanzibar', '2005-08-15'::timestamp, '{"signedFrom": "Kikosi Maalum cha Kuzuia Magendo FC", "joinedDate": "2025-07-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-abdulkarimkassimkiswanya-19', 'Abdulkarim Kassim Kiswanya', 'ftz-azam-abdulkarimkassimkiswanya-19', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'MF', 'admin', true, true, NOW(), NOW(), 'Abdulkarim', 'Kassim Kiswanya', 'Tanzania', '2005-02-24'::timestamp, '{"signedFrom": "Azam FC U19", "joinedDate": "2026-07-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", "shirtNumber", metadata) VALUES ('ftz-azam-sadiokanoute-20', 'Sadio Kanoute', 'ftz-azam-sadiokanoute-20', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CM', 'admin', true, true, NOW(), NOW(), 'Sadio', 'Kanoute', 'Mali', '1996-10-21'::timestamp, 186, 8, '{"foot": "right", "signedFrom": "Without Club", "contract": "2027-06-30", "joinedDate": "2025-08-11"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", "shirtNumber", metadata) VALUES ('ftz-azam-feisalsalum-21', 'Feisal Salum', 'ftz-azam-feisalsalum-21', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'AM', 'admin', true, true, NOW(), NOW(), 'Feisal', 'Salum', 'Tanzania', '1998-01-11'::timestamp, 178, 6, '{"foot": "right", "signedFrom": "Young Africans SC", "contract": "2027-06-30", "marketValueEUR": 300000, "joinedDate": "2023-07-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", "shirtNumber", metadata) VALUES ('ftz-azam-yahyazayd-22', 'Yahya Zayd', 'ftz-azam-yahyazayd-22', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'AM', 'admin', true, true, NOW(), NOW(), 'Yahya', 'Zayd', 'Tanzania', '1998-03-10'::timestamp, 177, 21, '{"signedFrom": "Without Club", "contract": "2026-10-30", "marketValueEUR": 50000, "joinedDate": "2022-01-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "shirtNumber", metadata) VALUES ('ftz-azam-iddyselemannado-23', 'Iddy Seleman Nado', 'ftz-azam-iddyselemannado-23', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'LW', 'admin', true, true, NOW(), NOW(), 'Iddy', 'Seleman Nado', 'Tanzania', '1995-03-11'::timestamp, 23, '{"foot": "left", "signedFrom": "Mbeya City Council FC", "marketValueEUR": 75000, "joinedDate": "2019-07-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "shirtNumber", metadata) VALUES ('ftz-azam-abdulhamisisuleiman-24', 'Abdul Hamisi Suleiman', 'ftz-azam-abdulhamisisuleiman-24', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'LW', 'admin', true, true, NOW(), NOW(), 'Abdul', 'Hamisi Suleiman', 'Tanzania', '2001-02-26'::timestamp, 9, '{"foot": "right", "signedFrom": "Coastal Union", "marketValueEUR": 50000, "joinedDate": "2022-07-04"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-kiprezunon-25', 'Kipre Zunon', 'ftz-azam-kiprezunon-25', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'LW', 'admin', true, true, NOW(), NOW(), 'Kipre', 'Zunon', 'Cote d''Ivoire', '1999-09-03'::timestamp, '{"foot": "right", "signedFrom": "MC Algiers", "joinedDate": "2026-07-05"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", metadata) VALUES ('ftz-azam-cheicknadiakite-26', 'Cheickna Diakite', 'ftz-azam-cheicknadiakite-26', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'LW', 'admin', true, true, NOW(), NOW(), 'Cheickna', 'Diakite', 'Mali', '2004-12-25'::timestamp, 175, '{"foot": "right", "signedFrom": "AS Real Bamako", "contract": "2027-06-30", "joinedDate": "2024-07-16"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-hassanmubiru-27', 'Hassan Mubiru', 'ftz-azam-hassanmubiru-27', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'RW', 'admin', true, true, NOW(), NOW(), 'Hassan', 'Mubiru', 'Uganda', '2004-07-25'::timestamp, '{"signedFrom": "Sports Club Villa Jogoo", "contract": "2028-06-30", "marketValueEUR": 175000, "joinedDate": "2026-07-20"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-henocmolia-28', 'Henoc Molia', 'ftz-azam-henocmolia-28', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'RW', 'admin', true, true, NOW(), NOW(), 'Henoc', 'Molia', 'DR Congo', '2004-01-01'::timestamp, '{"signedFrom": "FC Saint-Eloi Lupopo", "joinedDate": "2026-07-18"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "heightCm", "shirtNumber", metadata) VALUES ('ftz-azam-papedoudoudiallo-29', 'Pape Doudou Diallo', 'ftz-azam-papedoudoudiallo-29', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'RW', 'admin', true, true, NOW(), NOW(), 'Pape', 'Doudou Diallo', 'Senegal', '2002-12-26'::timestamp, 173, 13, '{"foot": "right", "signedFrom": "AS Academie Generation Foot", "contract": "2027-06-30", "joinedDate": "2025-07-30"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-johnmano-30', 'John Mano', 'ftz-azam-johnmano-30', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CF', 'admin', true, true, NOW(), NOW(), 'John', 'Mano', 'Sudan', '2001-12-12'::timestamp, '{"signedFrom": "Al-Akhdar SC", "marketValueEUR": 100000, "joinedDate": "2026-07-21"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "shirtNumber", metadata) VALUES ('ftz-azam-nassorsaadun-31', 'Nassor Saadun', 'ftz-azam-nassorsaadun-31', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'CF', 'admin', true, true, NOW(), NOW(), 'Nassor', 'Saadun', 'Tanzania', '2001-03-23'::timestamp, 29, '{"foot": "left", "signedFrom": "Geita Gold SC", "contract": "2026-07-01", "joinedDate": "2024-07-01"}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", metadata) VALUES ('ftz-azam-aimarhafidhabubakar-32', 'Aimar Hafidh Abubakar', 'ftz-azam-aimarhafidhabubakar-32', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'ST', 'admin', true, true, NOW(), NOW(), 'Aimar', 'Hafidh Abubakar', 'Tanzania', '2003-04-12'::timestamp, '{}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Player" (id, name, slug, "teamId", "leagueId", "sportId", position, source, verified, "isActive", "createdAt", "updatedAt", "firstName", "lastName", nationality, "dateOfBirth", "shirtNumber", metadata) VALUES ('ftz-azam-zidaneallysereri-33', 'Zidane Ally Sereri', 'ftz-azam-zidaneallysereri-33', 'ftz-azam', 'ftz-nbc-premier-league', (SELECT id FROM "Sport" WHERE name = 'Football' LIMIT 1), 'ST', 'admin', true, true, NOW(), NOW(), 'Zidane', 'Ally Sereri', 'Tanzania', '2005-11-20'::timestamp, 7, '{"signedFrom": "Dodoma Jiji FC", "joinedDate": "2025-01-11"}'::jsonb) ON CONFLICT (id) DO NOTHING;

COMMIT;